version: "3.9"

services:
    api01: &api
        image: kaikelfalcao/laravelfrakenrinha
        build: .
        depends_on:
            db:
                condition: service_healthy
        

    api02:
        <<: *api

    nginx:
        image: nginx:latest
        platform: "linux/arm64"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api01
            - api02
        ports:
            - "9999:9999"
        

    db:
        image: postgres
        hostname: db
        platform: "linux/arm64"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: rinha
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
        command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        

